# Generated by Django 5.1.3 on 2025-11-10 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('application_source', models.CharField(choices=[('walk_in', 'Walk-in'), ('online', 'Online Website')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('reapplication_date', models.DateField(blank=True, help_text='Date when applicant can reapply', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'db_table': 'applicants',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('id_document', 'ID Document'), ('certificate', 'Certificate'), ('other', 'Other')], max_length=20)),
                ('file_path', models.FileField(upload_to='applicant_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Applicant Document',
                'verbose_name_plural': 'Applicant Documents',
                'db_table': 'applicant_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
