# Generated by Django 5.1.3 on 2025-11-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('passed', 'Passed - Interview'), ('failed', 'Failed - Interview'), ('hired', 'Hired'), ('failed_training', 'Failed - Training'), ('failed_onboarding', 'Failed - Onboarding'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
    ]
