# Generated by Django 5.1.3 on 2025-11-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_alter_applicant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='distance_from_office',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance in meters from office', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Applicant's latitude during application", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Applicant's longitude during application", max_digits=9, null=True),
        ),
    ]
