# Generated by Django 5.1.3 on 2025-11-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0003_applicant_distance_from_office_applicant_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text="Applicant's latitude during application", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text="Applicant's longitude during application", max_digits=10, null=True),
        ),
    ]
