# Generated by Django 5.1.3 on 2025-11-12 16:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interview_submission_date_and_more'),
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processingqueue',
            name='processing_type',
            field=models.CharField(choices=[('bulk_analysis', 'Bulk Analysis'), ('single_video', 'Single Video'), ('reprocessing', 'Reprocessing')], default='bulk_analysis', help_text='Type of processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='processingqueue',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_queues', to='interviews.interview'),
        ),
        migrations.AlterField(
            model_name='processingqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
