# Generated by Django 5.1.3 on 2025-11-10 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('situational', 'Situational'), ('general', 'General')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order of the question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'db_table': 'interview_questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('initial_ai', 'Initial AI Interview'), ('technical', 'Technical Interview'), ('final', 'Final Interview')], default='initial_ai', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applicants.applicant')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'db_table': 'interviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_path', models.FileField(upload_to='video_responses/%Y/%m/%d/')),
                ('duration', models.DurationField(help_text='Duration of the video response')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_responses', to='interviews.interview')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interviews.interviewquestion')),
            ],
            options={
                'verbose_name': 'Video Response',
                'verbose_name_plural': 'Video Responses',
                'db_table': 'video_responses',
                'ordering': ['interview', 'question__order'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_text', models.TextField(help_text='Transcribed text from video')),
                ('sentiment_score', models.FloatField(default=0.0, help_text='Sentiment analysis score')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Response confidence score')),
                ('body_language_analysis', models.JSONField(default=dict, help_text='Body language analysis data')),
                ('speech_clarity_score', models.FloatField(default=0.0, help_text='Speech clarity score')),
                ('content_relevance_score', models.FloatField(default=0.0, help_text='Content relevance score')),
                ('overall_score', models.FloatField(default=0.0, help_text='Overall score out of 100')),
                ('recommendation', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('review', 'Needs Review')], max_length=10)),
                ('langchain_analysis_data', models.JSONField(default=dict, help_text='Raw LangChain/Gemini analysis data')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('video_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='interviews.videoresponse')),
            ],
            options={
                'verbose_name': 'AI Analysis',
                'verbose_name_plural': 'AI Analyses',
                'db_table': 'ai_analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
