# Generated by Django 5.1.3 on 2025-11-12 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='submission_date',
            field=models.DateTimeField(blank=True, help_text='When applicant submitted all responses', null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='max_duration',
            field=models.DurationField(blank=True, help_text='Maximum duration for answer', null=True),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='ai_score',
            field=models.FloatField(blank=True, help_text='AI-generated score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='hr_comments',
            field=models.TextField(blank=True, help_text='HR comments on the response'),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='hr_override_score',
            field=models.IntegerField(blank=True, help_text='HR can override AI score if incorrect', null=True),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='hr_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='hr_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='sentiment',
            field=models.FloatField(blank=True, help_text='Sentiment score', null=True),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='transcript',
            field=models.TextField(blank=True, help_text='Transcribed text from video'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='videoresponse',
            unique_together={('interview', 'question')},
        ),
    ]
