# Generated by Django 5.1.3 on 2025-11-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interview_submission_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='authenticity_flag',
            field=models.BooleanField(default=False, help_text='True if any questions flagged for script reading'),
        ),
        migrations.AddField(
            model_name='interview',
            name='authenticity_notes',
            field=models.TextField(blank=True, help_text='HR notes on authenticity investigation'),
        ),
        migrations.AddField(
            model_name='interview',
            name='authenticity_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('under_investigation', 'Under Investigation'), ('failed_authenticity', 'Failed Authenticity Check')], default='verified', help_text='Overall authenticity status of interview', max_length=20),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='script_reading_data',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed gaze tracking data (camera %, directions, patterns)'),
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='script_reading_status',
            field=models.CharField(blank=True, choices=[('clear', 'Clear'), ('suspicious', 'Suspicious'), ('high_risk', 'High Risk')], help_text='Script reading detection result', max_length=20, null=True),
        ),
    ]
