# Generated by Django 5.1.3 on 2025-11-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interview_authenticity_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='position_type',
            field=models.CharField(choices=[('virtual_assistant', 'Virtual Assistant'), ('customer_service', 'Customer Service'), ('it_support', 'IT Support'), ('sales_marketing', 'Sales and Marketing'), ('general', 'General')], default='general', help_text='Job position this question is designed for', max_length=30),
        ),
    ]
