# Generated by Django 5.1.3 on 2025-11-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_add_position_type_to_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='position_type',
            field=models.CharField(blank=True, choices=[('virtual_assistant', 'Virtual Assistant'), ('customer_service', 'Customer Service'), ('it_support', 'IT Support'), ('sales_marketing', 'Sales and Marketing'), ('general', 'General')], default='general', help_text='Position type selected for this interview', max_length=30, null=True),
        ),
    ]
