# Generated by Django 5.1.3 on 2025-11-14 14:16

import django.db.models.deletion
from django.db import migrations, models


def populate_types(apps, schema_editor):
    """Populate PositionType and QuestionType tables"""
    PositionType = apps.get_model('interviews', 'PositionType')
    QuestionType = apps.get_model('interviews', 'QuestionType')
    
    # Create position types
    position_types = [
        {'code': 'virtual_assistant', 'name': 'Virtual Assistant', 'order': 1},
        {'code': 'customer_service', 'name': 'Customer Service', 'order': 2},
        {'code': 'it_support', 'name': 'IT Support', 'order': 3},
        {'code': 'sales_marketing', 'name': 'Sales and Marketing', 'order': 4},
        {'code': 'general', 'name': 'General', 'order': 5},
    ]
    for pt in position_types:
        PositionType.objects.create(**pt)
    
    # Create question types
    question_types = [
        {'code': 'technical', 'name': 'Technical', 'order': 1},
        {'code': 'behavioral', 'name': 'Behavioral', 'order': 2},
        {'code': 'situational', 'name': 'Situational', 'order': 3},
        {'code': 'general', 'name': 'General', 'order': 4},
    ]
    for qt in question_types:
        QuestionType.objects.create(**qt)


def migrate_question_data(apps, schema_editor):
    """Migrate InterviewQuestion CharField data to ForeignKey IDs"""
    InterviewQuestion = apps.get_model('interviews', 'InterviewQuestion')
    PositionType = apps.get_model('interviews', 'PositionType')
    QuestionType = apps.get_model('interviews', 'QuestionType')
    
    for question in InterviewQuestion.objects.all():
        # Map old CharField values to new FK objects
        if question.position_type_temp:
            try:
                position = PositionType.objects.get(code=question.position_type_temp)
                question.position_type = position
            except PositionType.DoesNotExist:
                # If code doesn't exist, use general
                question.position_type = PositionType.objects.get(code='general')
        
        if question.question_type_temp:
            try:
                q_type = QuestionType.objects.get(code=question.question_type_temp)
                question.question_type = q_type
            except QuestionType.DoesNotExist:
                # If code doesn't exist, use general
                question.question_type = QuestionType.objects.get(code='general')
        
        question.save()


def migrate_interview_data(apps, schema_editor):
    """Migrate Interview CharField data to ForeignKey IDs"""
    Interview = apps.get_model('interviews', 'Interview')
    PositionType = apps.get_model('interviews', 'PositionType')
    
    for interview in Interview.objects.filter(position_type_temp__isnull=False):
        try:
            position = PositionType.objects.get(code=interview.position_type_temp)
            interview.position_type = position
            interview.save()
        except PositionType.DoesNotExist:
            pass  # Leave as null if code doesn't exist


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_add_position_type_to_interview'),
    ]

    operations = [
        # Step 1: Create new models
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique code for the position type (e.g., 'virtual_assistant')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name for the position type (e.g., 'Virtual Assistant')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the position type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this position type is available for selection')),
                ('order', models.IntegerField(default=0, help_text='Display order in dropdowns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Position Type',
                'verbose_name_plural': 'Position Types',
                'db_table': 'position_types',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique code for the question type (e.g., 'technical')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name for the question type (e.g., 'Technical')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the question type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question type is available for selection')),
                ('order', models.IntegerField(default=0, help_text='Display order in dropdowns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question Type',
                'verbose_name_plural': 'Question Types',
                'db_table': 'question_types',
                'ordering': ['order', 'name'],
            },
        ),
        
        # Step 2: Populate the new tables
        migrations.RunPython(populate_types, reverse_code=migrations.RunPython.noop),
        
        # Step 3: Rename old CharField fields
        migrations.RenameField(
            model_name='interviewquestion',
            old_name='position_type',
            new_name='position_type_temp',
        ),
        migrations.RenameField(
            model_name='interviewquestion',
            old_name='question_type',
            new_name='question_type_temp',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='position_type',
            new_name='position_type_temp',
        ),
        
        # Step 4: Add new ForeignKey fields (nullable)
        migrations.AddField(
            model_name='interviewquestion',
            name='position_type',
            field=models.ForeignKey(help_text='Job position this question is designed for', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='interviews.positiontype'),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='question_type',
            field=models.ForeignKey(help_text='Type of question', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='interviews.questiontype'),
        ),
        migrations.AddField(
            model_name='interview',
            name='position_type',
            field=models.ForeignKey(blank=True, help_text='Position type selected for this interview', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interviews', to='interviews.positiontype'),
        ),
        
        # Step 5: Migrate data from temp fields to new ForeignKeys
        migrations.RunPython(migrate_question_data, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(migrate_interview_data, reverse_code=migrations.RunPython.noop),
        
        # Step 6: Remove temp fields
        migrations.RemoveField(
            model_name='interviewquestion',
            name='position_type_temp',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='question_type_temp',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='position_type_temp',
        ),
        
        # Step 7: Make ForeignKeys non-nullable for InterviewQuestion (Interview can stay nullable)
        migrations.AlterField(
            model_name='interviewquestion',
            name='position_type',
            field=models.ForeignKey(help_text='Job position this question is designed for', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='interviews.positiontype'),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='question_type',
            field=models.ForeignKey(help_text='Type of question', on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='interviews.questiontype'),
        ),
    ]
