# Generated by Django 5.1.3 on 2025-11-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_positiontype_questiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positiontype',
            name='address',
            field=models.CharField(blank=True, help_text='Work location or address (optional)', max_length=255),
        ),
        migrations.AddField(
            model_name='positiontype',
            name='employment_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], default='Full-time', help_text='Full-time or Part-time', max_length=20),
        ),
        migrations.AddField(
            model_name='positiontype',
            name='key_responsibilities',
            field=models.TextField(blank=True, help_text='Key responsibilities for the role (optional)'),
        ),
        migrations.AddField(
            model_name='positiontype',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Qualifications for the role (optional)'),
        ),
        migrations.AddField(
            model_name='positiontype',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Required skills for the role (optional)'),
        ),
        migrations.AddField(
            model_name='positiontype',
            name='salary',
            field=models.CharField(blank=True, help_text='Salary range or amount (optional)', max_length=50),
        ),
        migrations.AlterField(
            model_name='positiontype',
            name='description',
            field=models.TextField(blank=True, help_text='About the Role / Description of the position type'),
        ),
    ]
