# Generated by Django 5.1.3 on 2025-11-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_positiontype_address_positiontype_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if processing failed', null=True),
        ),
    ]
