# Generated by Django 5.1.3 on 2025-11-18 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0006_positiontype_questiontype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTokenSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_input_tokens', models.BigIntegerField(default=0)),
                ('total_output_tokens', models.BigIntegerField(default=0)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transcription_requests', models.IntegerField(default=0)),
                ('transcription_tokens', models.BigIntegerField(default=0)),
                ('transcription_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('analysis_requests', models.IntegerField(default=0)),
                ('analysis_tokens', models.BigIntegerField(default=0)),
                ('analysis_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_response_time', models.FloatField(default=0, help_text='Average API response time in seconds')),
                ('success_rate', models.FloatField(default=100, help_text='Percentage of successful requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Token Summaries',
                'db_table': 'monitoring_daily_summary',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('transcription', 'Video Transcription'), ('analysis', 'Transcript Analysis'), ('batch_analysis', 'Batch Analysis'), ('other', 'Other')], max_length=50)),
                ('input_tokens', models.IntegerField(default=0, help_text='Tokens sent to API (prompt)')),
                ('output_tokens', models.IntegerField(default=0, help_text='Tokens received from API (response)')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens used')),
                ('model_name', models.CharField(default='gemini-2.5-flash', max_length=100)),
                ('api_response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, help_text='Estimated cost in USD', max_digits=10)),
                ('prompt_length', models.IntegerField(default=0, help_text='Character count of prompt')),
                ('response_length', models.IntegerField(default=0, help_text='Character count of response')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='interviews.interview')),
                ('video_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='interviews.videoresponse')),
            ],
            options={
                'db_table': 'monitoring_token_usage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='monitoring__created_746d57_idx'), models.Index(fields=['operation_type'], name='monitoring__operati_433f22_idx'), models.Index(fields=['interview'], name='monitoring__intervi_4019f0_idx')],
            },
        ),
    ]
